# Generated by Django 5.2.6 on 2025-10-09 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities.city', verbose_name='Город филиала'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='segment',
            field=models.CharField(blank=True, choices=[('retail', 'Розница'), ('wholesale', 'Опт'), ('vip', 'VIP')], max_length=20, verbose_name='Сегмент'),
        ),
    ]
