# Generated by Django 5.2.6 on 2025-10-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_branch_product_branch_warehouse_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assortment_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ассортиментная группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размерность'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_plan_selection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отбор плана продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonality',
            field=models.CharField(blank=True, choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], max_length=20, verbose_name='Сезонность'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_type',
            field=models.CharField(blank=True, choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], max_length=20, verbose_name='Тип шины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='products.productgroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'db_table': 'product_groups',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productgroup', verbose_name='Группа товаров'),
        ),
    ]
