# Generated by Django 5.2.6 on 2025-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_promotional_price_product_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tire_type',
            field=models.CharField(blank=True, choices=[('Легковая', 'Легковая'), ('Грузовая', 'Грузовая'), ('Легкогрузовая', 'Легкогрузовая'), ('Индустриальные', 'Индустриальные'), ('КГШ', 'КГШ'), ('Сельскохозяйственная', 'Сельскохозяйственная'), ('Мотошины', 'Мотошины'), ('Квадроциклы', 'Квадроциклы')], max_length=20, verbose_name='Тип шины'),
        ),
    ]
