# Generated by Django 5.2.6 on 2025-10-09 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('message', models.TextField(verbose_name='Изменение')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Изменение заказа',
                'verbose_name_plural': 'Изменения заказа',
                'ordering': ['-changed_at'],
            },
        ),
    ]
