# Generated by Django 5.2.6 on 2025-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('new_paid', 'Новый оплаченный'), ('reserve', 'Резерв'), ('transfer', 'Перемещение'), ('delivery', 'Доставка'), ('callback', 'Перезвонить'), ('completed', 'Выполнен'), ('refund', 'Возврат средств'), ('cancelled', 'Отменён (указать причину)'), ('cancel_no_answer', 'Отменен — не дозвонился'), ('cancel_not_suitable_year', 'Отменен — не устроил год'), ('cancel_wrong_order', 'Отменен — ошибочный заказ'), ('cancel_found_other', 'Отменен — нашел другие'), ('cancel_delivery_terms', 'Отменен — условия доставки'), ('cancel_no_quantity', 'Отменен — нет нужного кол-ва'), ('cancel_incomplete', 'Отменен — не комплект')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='OrderChange',
        ),
    ]
