# Generated by Django 5.2.6 on 2025-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_delete_orderchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_level',
            field=models.CharField(choices=[('wholesale', 'Оптовая'), ('promotional', 'Акционная'), ('retail', 'Розничная')], default='retail', max_length=20, verbose_name='Уровень цен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('airba', 'Airba Pay'), ('halyk', 'Halyk'), ('kaspi', 'Kaspi'), ('woopay', 'Wooppay'), ('bcc', 'БЦК'), ('cassa', 'На кассе'), ('account', 'По счету'), ('installment', 'Рассрочка (сайт)'), ('site', 'Сайт'), ('card', 'Карта'), ('transfer', 'Перевод'), ('cash', 'Наличные')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('callcentr', 'Call-центр 2710'), ('2gis', '2GIS WhatsApp'), ('email', 'E-mail'), ('instagram', 'Instagram'), ('kaspi', 'Kaspi'), ('whatsapp', 'WhatsApp'), ('website', 'Сайт')], max_length=20, verbose_name='Откуда заказ'),
        ),
    ]
