# Generated by Django 5.2.6 on 2025-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_price_level_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tire_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип шины'),
        ),
    ]
