# Generated by Django 5.2.6 on 2025-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_tire_type'),
    ]

    operations = [
        # Индексы для таблицы Order
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders_order (created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_orders_created_at;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orders_status ON orders_order (status);",
            reverse_sql="DROP INDEX IF EXISTS idx_orders_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orders_client_id ON orders_order (client_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_orders_client_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orders_responsible_id ON orders_order (responsible_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_orders_responsible_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders_order (order_number);",
            reverse_sql="DROP INDEX IF EXISTS idx_orders_order_number;"
        ),
        
        # Индексы для таблицы OrderItem
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orderitems_order_id ON orders_orderitem (order_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_orderitems_order_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orderitems_product_id ON orders_orderitem (product_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_orderitems_product_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orderitems_product_code ON orders_orderitem (product_code);",
            reverse_sql="DROP INDEX IF EXISTS idx_orderitems_product_code;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orderitems_segment ON orders_orderitem (segment);",
            reverse_sql="DROP INDEX IF EXISTS idx_orderitems_segment;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_orderitems_branch_city ON orders_orderitem (branch_city);",
            reverse_sql="DROP INDEX IF EXISTS idx_orderitems_branch_city;"
        ),
    ]
