# Generated by Django 5.2.6 on 2025-11-06 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(choices=[('K', 'Командировка'), ('B', 'Больничный'), ('A', 'Без содержания'), ('O', 'Отпуск'), ('V', 'Выходной')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['user', 'date'], name='timeclock_w_user_id_0ca2e9_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
