# Generated by Django 5.2.6 on 2025-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_workdaymark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdaymark',
            name='code',
            field=models.CharField(choices=[('К', 'Командировка'), ('Б', 'Больничный'), ('А', 'Без содержания'), ('О', 'Отпуск'), ('В', 'Выходной')], max_length=1),
        ),
    ]
