# Generated by Django 5.2.6 on 2025-11-01 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "План июнь 2025"', max_length=200, verbose_name='Название плана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'db_table': 'plans',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='Целевое количество заказов')),
                ('target_sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Целевая сумма')),
                ('criteria_operator', models.CharField(choices=[('both', 'Оба критерия (кол-во и сумма)'), ('either', 'Любой критерий (кол-во или сумма)')], default='both', max_length=10, verbose_name='Условие выполнения')),
                ('achieved_count', models.PositiveIntegerField(default=0, verbose_name='Достигнуто заказов')),
                ('achieved_sum', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Достигнутая сумма')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='plans.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Назначение плана',
                'verbose_name_plural': 'Назначения планов',
                'db_table': 'plan_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['start_date', 'end_date'], name='plans_start_d_129ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_by', '-created_at'], name='plans_created_f1f7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='planassignment',
            index=models.Index(fields=['plan', 'manager'], name='plan_assign_plan_id_e21f20_idx'),
        ),
        migrations.AddIndex(
            model_name='planassignment',
            index=models.Index(fields=['manager', 'is_achieved'], name='plan_assign_manager_b42c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planassignment',
            unique_together={('plan', 'manager')},
        ),
    ]
