# Generated by Django 5.2.6 on 2025-09-21 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], max_length=20, verbose_name='Тип клиента')),
                ('name', models.CharField(default='Клиент', max_length=255, verbose_name='ФИО/Название')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_clients', to=settings.AUTH_USER_MODEL, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
                'db_table': 'client_addresses',
            },
        ),
        migrations.CreateModel(
            name='ClientCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер')),
                ('vin_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN номер')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Автомобиль клиента',
                'verbose_name_plural': 'Автомобили клиентов',
                'db_table': 'client_cars',
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phones', to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_phones', to=settings.AUTH_USER_MODEL, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Телефон клиента',
                'verbose_name_plural': 'Телефоны клиентов',
                'db_table': 'client_phones',
            },
        ),
        migrations.CreateModel(
            name='IndividualClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('passport_issued', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан паспорт')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_data', to='clients.client')),
            ],
            options={
                'verbose_name': 'Данные физического лица',
                'verbose_name_plural': 'Данные физических лиц',
                'db_table': 'individual_client_data',
            },
        ),
        migrations.CreateModel(
            name='LegalEntityClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('bin', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='БИН')),
                ('tax_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Налоговый номер')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО директора')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Банковский счет')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_data', to='clients.client')),
            ],
            options={
                'verbose_name': 'Данные юридического лица',
                'verbose_name_plural': 'Данные юридических лиц',
                'db_table': 'legal_entity_client_data',
            },
        ),
    ]
