# Generated by Django 5.2.6 on 2025-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город клиента',
                'verbose_name_plural': 'Города клиентов',
                'db_table': 'client_cities',
            },
        ),
        migrations.CreateModel(
            name='ProductSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сегмент товара',
                'verbose_name_plural': 'Сегменты товаров',
                'db_table': 'product_segments',
            },
        ),
    ]
